### ISSUE TITLE
Bug: Deja de mandar al recibir IniciarJuego en un juego iniciado

### ISSUE THREAD

**Issue by luchowaldman** [luchowaldman/elpibegravedad#100]
Bug: Deja de mandar al recibir IniciarJuego en un juego iniciado

**Comment by FrancoLiberali** [comment]
Se confirma el reporte, al presionar el boton "I" durante una partida ya comenzada, el servidor queda bloqueado
![Screenshot 2024-11-24 at 7 51 58 PM](https://github.com/user-attachments/assets/f3a332c1-74c0-4b80-a186-4dfb9a085371)
<img width="1008" alt="Screenshot 2024-11-24 at 7 52 10 PM" src="https://github.com/user-attachments/assets/e5c2851e-1296-43b2-8957-b737ed42c2f9">
