### ISSUE TITLE
Cargar mapa en libreria de colisiones

### ISSUE THREAD

**Issue by FrancoLiberali** [luchowaldman/elpibegravedad#21]
A partir de la estructura en memoria obtenida de https://github.com/luchowaldman/elpibegravedad/issues/19, cargar en la libreria elegida en https://github.com/luchowaldman/elpibegravedad/issues/20 los datos del mapa para poder detectar colisiones con el mapa

**Comment by FrancoLiberali** [comment]
obstaculos son simpre cuadradros, el hasta x y hasta y son la esquina superior izquierda
los pisos tienen de medida 100*10, por lo que el alto es fijo de 10

**Comment by FrancoLiberali** [comment]
personaje: 70*100

**Comment by FrancoLiberali** [comment]
A hablar con luis 
- coordenadas tienen algo raro
- plataformas deben estar mas lejos del limite
- personaje y obstaculo demaciado grandes
- piso y techo no tiene sentido
- para el server todo es plataforma, no hay ninguna diferencia

**Comment by luchowaldman** [comment]
Franco:
coordenadas tienen algo raro: Si, lo vi. El tema es que las coordenadas que le pasas a Phaser indican el centro de la imagen. Para arreglar eso tenemos que agregar en  el mapa las dimensiones de la imagen, lo que tampoco esta mal.
plataformas deben estar mas lejos del limite: No entiendo! 
personaje y obstaculo demaciado grandes: totalmente con respecto al personaje (las imagenes las manejamos desde el mapa). ¿lo reducimos a la mitad? ¿35x50?
piso y techo no tiene sentido para el server todo es plataforma, no hay ninguna diferencia: el cliente lo dibuja distinto (e imagino que no esta de mas que lo guarde el server por si quisieramos que tenga alguna jugabilidad: onda piso acelerador o enlentecedor)
