### ISSUE TITLE
Mostrar resultados al recibir mensaje carreraTerminada

### ISSUE THREAD

**Issue by FrancoLiberali** [luchowaldman/elpibegravedad#52]
En el ticket https://github.com/luchowaldman/elpibegravedad/issues/45 se introdujo un nuevo mensaje "carreraTerminada" que se envia cuando la carrera terminó. La misma contiene una lista con los resultados finales de la carrera y deberia ser mostrada en la pantalla

**Comment by luchowaldman** [comment]
Agrego la administracion de carreraTerminadaHandler en cliente y en 
Agrego la accion grafica: AccionGraficaSetPosicionTexto
