### ISSUE TITLE
Dejar de mostrar jugador al tener "estaMuerto"

### ISSUE THREAD

**Issue by FrancoLiberali** [luchowaldman/elpibegravedad#53]
En https://github.com/luchowaldman/elpibegravedad/issues/29 se determina que se le agregará al mensaje "tick" el campo "estaMuerto" para saber cuando un jugador esta muerto. Este campo debe ser tenido en cuenta en el cliente para dejar de mostrar este personaje

**Comment by luchowaldman** [comment]
Agrego la imagen de "jugador muerto"
Agrego el manejo de Jugador_Muerto en la clase player
