### ISSUE TITLE
Mostrar meta en el mapa

### ISSUE THREAD

**Issue by FrancoLiberali** [luchowaldman/elpibegravedad#54]
Como parte de https://github.com/luchowaldman/elpibegravedad/issues/45, se agregó al mapa el nuevo campo "meta". La misma debe ser dibujada en el cliente para que se entienda cuando un usuario pasó la meta

**Comment by luchowaldman** [comment]
Agrego la imagen de Meta
Agrego la clase de Meta
Dibujo la meta cuando dibuja el mapa
