### ISSUE TITLE
Correccion: Correr el momendo de muerte del personaje

### ISSUE THREAD

**Issue by luchowaldman** [luchowaldman/elpibegravedad#79]
Correr el momendo de muerte del personaje por alejarse del primero para que se vea

**Comment by FrancoLiberali** [comment]
Que el personaje se muera cuando tiene la mitad del cuerpo fuera de la pantalla

**Comment by FrancoLiberali** [comment]
Finalmente se decide hacerlo que apenas toca el limite para que sea mas claro
